// src-react/components/cooking/RecipeGrid.tsx
import type { Recipe } from '../../../src/data/schemas/recipe'

export interface RecipeGridProps {
  recipes: Recipe[]
  selectedCounts: Record<string, number>
  getItemName: (id: string) => string
  getItemImageUrl: (id: string) => string
  handleImageError: (event: React.SyntheticEvent<HTMLImageElement>) => void
  onChangeCount: (id: string, count: number) => void
}

export function RecipeGrid({
  recipes,
  selectedCounts,
  getItemName,
  getItemImageUrl,
  handleImageError,
  onChangeCount,
}: RecipeGridProps) {
  function increment(id: string) {
    const current = selectedCounts[id] ?? 0
    onChangeCount(id, current + 1)
  }

  function decrement(id: string) {
    const current = selectedCounts[id] ?? 0
    onChangeCount(id, Math.max(0, current - 1))
  }

  function handleCountChange(id: string, value: string) {
    const parsed = Number(value)
    const next = Number.isFinite(parsed) ? Math.max(0, parsed) : 0
    onChangeCount(id, next)
  }

  return (
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
      {recipes.map((recipe) => (
        <div
          key={recipe.id}
          className="rounded border border-border bg-card p-3 transition-shadow hover:shadow-sm"
        >
          <div className="flex items-start gap-3">
            <img
              src={getItemImageUrl(recipe.resultItemId)}
              alt={recipe.name}
              className="h-12 w-12 rounded object-cover"
              onError={handleImageError}
            />
            <div className="min-w-0 flex-1">
              <div className="flex items-center justify-between">
                <div className="truncate font-semibold text-foreground">{recipe.name}</div>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    className="rounded border border-border bg-background px-2 py-1 text-foreground hover:bg-accent"
                    onClick={() => decrement(recipe.id)}
                  >
                    -
                  </button>
                  <input
                    type="number"
                    min={0}
                    className="w-16 rounded border border-border bg-background px-2 py-1 text-center text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-ring"
                    value={selectedCounts[recipe.id] ?? 0}
                    onChange={(event) => handleCountChange(recipe.id, event.target.value)}
                  />
                  <button
                    type="button"
                    className="rounded border border-border bg-background px-2 py-1 text-foreground hover:bg-accent"
                    onClick={() => increment(recipe.id)}
                  >
                    +
                  </button>
                </div>
              </div>
              <div className="mt-2 grid grid-cols-1 gap-1 text-sm sm:grid-cols-2">
                {recipe.requiredItems.map((required) => (
                  <div key={required.itemId} className="flex items-center gap-2">
                    <img
                      src={getItemImageUrl(required.itemId)}
                      alt={getItemName(required.itemId)}
                      className="h-5 w-5 rounded object-cover"
                      onError={handleImageError}
                    />
                    <span className="truncate text-foreground">{getItemName(required.itemId)}</span>
                    <span className="ml-auto text-muted-foreground">x{required.quantity}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      ))}
    </div>
  )
}

export default RecipeGrid

// src/components/cooking/RecipeGrid.vue
<template>
  <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
    <div v-for="recipe in recipes" :key="recipe.id" class="border border-border rounded p-3 hover:shadow-sm bg-card">
      <div class="flex items-start gap-3">
        <img :src="getItemImageUrl(recipe.resultItemId)" :alt="recipe.name" class="w-12 h-12 rounded object-cover"
          @error="handleImageError" />
        <div class="flex-1 min-w-0">
          <div class="flex items-center justify-between">
            <div class="truncate">
              <div class="font-semibold text-foreground">{{ recipe.name }}</div>
            </div>
            <div class="flex items-center gap-2">
              <button type="button"
                class="px-2 py-1 border border-border rounded text-foreground hover:bg-accent bg-background"
                @click="decrementCount(recipe.id)">-</button>
              <input type="number" min="0"
                class="w-16 text-center px-2 py-1 border border-border rounded bg-background text-foreground"
                :value="selectedCounts[recipe.id] ?? 0"
                @input="onChange(recipe.id, ($event.target as HTMLInputElement).value)" />
              <button type="button"
                class="px-2 py-1 border border-border rounded text-foreground hover:bg-accent bg-background"
                @click="incrementCount(recipe.id)">+</button>
            </div>
          </div>
          <div class="mt-2 grid grid-cols-1 sm:grid-cols-2 gap-1 text-sm">
            <div v-for="ri in recipe.requiredItems" :key="ri.itemId" class="flex items-center gap-2">
              <img :src="getItemImageUrl(ri.itemId)" :alt="getItemName(ri.itemId)" class="w-5 h-5 rounded object-cover"
                @error="handleImageError" />
              <span class="text-foreground truncate">{{ getItemName(ri.itemId) }}</span>
              <span class="ml-auto text-muted-foreground">x{{ ri.quantity }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Recipe } from '@/data/schemas/recipe'

const props = withDefaults(defineProps<{
  recipes: Recipe[]
  selectedCounts: Record<string, number>
  getItemName: (id: string) => string
  getItemImageUrl: (id: string) => string
  handleImageError: (e: Event) => void
}>(), {
  recipes: () => [],
  selectedCounts: () => ({} as Record<string, number>)
})

const emit = defineEmits<{
  (ev: 'changeCount', id: string, count: number): void
}>()

function onChange(id: string, val: string) {
  const n = Math.max(0, Number(val) || 0)
  emit('changeCount', id, n)
}

function incrementCount(id: string) {
  const current = props.selectedCounts[id] ?? 0
  emit('changeCount', id, current + 1)
}

function decrementCount(id: string) {
  const current = props.selectedCounts[id] ?? 0
  emit('changeCount', id, Math.max(0, current - 1))
}
</script>
