// src/components/ui/select.vue
<template>
  <div :class="cn('relative', props.class)" data-select>
    <slot />
  </div>
</template>

<script setup lang="ts">
import { provide, ref, watch } from 'vue'
import { cn } from '@/lib/utils'

export interface SelectProps {
  modelValue?: string
  value?: string
  defaultValue?: string
  class?: string
}

const props = withDefaults(defineProps<SelectProps>(), {
  defaultValue: '',
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  'update:value': [value: string]
}>()

const selectedValue = ref(props.modelValue || props.value || props.defaultValue)
const isOpen = ref(false)

// v-model을 위한 watch
watch(() => props.modelValue, (newValue) => {
  if (newValue !== undefined) {
    selectedValue.value = newValue
  }
})

watch(() => props.value, (newValue) => {
  if (newValue !== undefined) {
    selectedValue.value = newValue
  }
})

const updateValue = (value: string) => {
  selectedValue.value = value
  isOpen.value = false
  emit('update:modelValue', value)
  emit('update:value', value)
}

const toggleOpen = () => {
  isOpen.value = !isOpen.value
}

const close = () => {
  isOpen.value = false
}

provide('select', {
  selectedValue,
  isOpen,
  updateValue,
  toggleOpen,
  close,
})
</script>

// src/components/ui/select/Select.tsx
import type { PropsWithChildren } from 'react'
import { useCallback, useMemo, useRef, useState } from 'react'

import { cn } from '../../../lib/utils'
import { SelectContext } from './SelectContext'

export interface SelectProps extends PropsWithChildren {
  value?: string
  defaultValue?: string
  onValueChange?: (value: string) => void
  className?: string
}

export function Select({
  value,
  defaultValue = '',
  onValueChange,
  className,
  children,
}: SelectProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const isControlled = value !== undefined
  const [internalValue, setInternalValue] = useState(defaultValue)
  const [isOpen, setIsOpen] = useState(false)

  const selectedValue = isControlled ? value! : internalValue

  const setValue = useCallback(
    (nextValue: string) => {
      if (!isControlled) {
        setInternalValue(nextValue)
      }
      onValueChange?.(nextValue)
      setIsOpen(false)
    },
    [isControlled, onValueChange],
  )

  const toggleOpen = useCallback(() => {
    setIsOpen((prev) => !prev)
  }, [])

  const close = useCallback(() => {
    setIsOpen(false)
  }, [])

  const contextValue = useMemo(
    () => ({
      value: selectedValue,
      isOpen,
      toggleOpen,
      close,
      setValue,
    }),
    [selectedValue, isOpen, toggleOpen, close, setValue],
  )

  return (
    <SelectContext.Provider value={contextValue}>
      <div
        ref={containerRef}
        className={cn('relative', className)}
        data-select
      >
        {children}
      </div>
    </SelectContext.Provider>
  )
}
