// src/views/data/components/NPCList.vue
<template>
  <div class="space-y-4">
    <!-- 검색 및 필터 -->
    <div class="flex flex-col sm:flex-row gap-4">
      <!-- 검색 입력 -->
      <div class="flex-1">
        <Input
          v-model="searchQuery"
          placeholder="NPC 이름, 설명, 위치로 검색..."
          class="w-full"
        />
      </div>
      
      <!-- 위치 필터 -->
      <div class="flex gap-2">
        <Select v-model:value="selectedLocation">
          <SelectTrigger class="w-40">
            <SelectValue placeholder="위치 선택" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="">전체</SelectItem>
            <SelectItem
              v-for="location in npcStore.uniqueLocations"
              :key="location.id"
              :value="location.id"
            >
              {{ location.name }} ({{ npcStore.locationCounts[location.id] || 0 }})
            </SelectItem>
          </SelectContent>
        </Select>
        
        <!-- 물물교환 필터 -->
        <Select v-model:value="tradeFilter">
          <SelectTrigger class="w-32">
            <SelectValue placeholder="교환 여부" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="">전체</SelectItem>
            <SelectItem value="true">교환 가능</SelectItem>
            <SelectItem value="false">교환 불가</SelectItem>
          </SelectContent>
        </Select>
      </div>
    </div>

    <!-- 결과 개수 표시 -->
    <div class="text-sm text-muted-foreground">
      총 {{ filteredNPCs.length }}개의 NPC
    </div>

    <!-- NPC 그리드 -->
    <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 2xl:grid-cols-8 gap-3">
      <div
        v-for="npc in filteredNPCs"
        :key="npc.id"
        class="bg-card border rounded-lg p-3 hover:shadow-md transition-shadow cursor-pointer"
        @click="selectNPC(npc)"
      >
        <!-- NPC 이미지 -->
        <div class="aspect-square mb-2 bg-muted rounded-lg flex items-center justify-center overflow-hidden">
          <img
            v-if="npc.imageUrl"
            :src="npc.imageUrl"
            :alt="npc.name"
            class="w-full h-full object-cover"
            @error="handleImageError"
          />
          <div v-else class="text-muted-foreground text-xs">
            이미지 없음
          </div>
        </div>

        <!-- NPC 정보 -->
        <div class="space-y-1">
          <h3 class="font-semibold text-sm">{{ npc.name }}</h3>
          <p class="text-xs text-muted-foreground line-clamp-2">{{ npc.description }}</p>
          <p class="text-xs text-muted-foreground">{{ npc.location.name }}</p>
          
          <!-- 물물교환 정보 -->
          <div v-if="npc.tradeCount > 0" class="flex items-center gap-1 text-xs text-blue-600">
            <span>교환 가능</span>
            <span class="bg-blue-100 text-blue-800 px-1 py-0.5 rounded-full text-xs">
              {{ npc.tradeCount }}개
            </span>
          </div>
          <div v-else class="text-xs text-muted-foreground">
            교환 불가
          </div>
        </div>
      </div>
    </div>

    <!-- 빈 상태 -->
    <div v-if="filteredNPCs.length === 0" class="text-center py-12">
      <div class="text-muted-foreground">
        <p class="text-lg font-medium">NPC를 찾을 수 없습니다</p>
        <p class="text-sm">검색어나 필터를 변경해보세요</p>
      </div>
    </div>

    <!-- NPC 상세 정보 Sheet -->
    <NPCDetailSheet
      :open="sheetOpen"
      :selected-npc="selectedNpc"
      @update:open="sheetOpen = $event"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useNpcStore } from '@/stores/npc'
import type { EnrichedNPC } from '@/stores/npc'
import Input from '@/components/ui/input.vue'
import Select from '@/components/ui/select.vue'
import SelectContent from '@/components/ui/select-content.vue'
import SelectItem from '@/components/ui/select-item.vue'
import SelectTrigger from '@/components/ui/select-trigger.vue'
import SelectValue from '@/components/ui/select-value.vue'
import NPCDetailSheet from './NPCDetailSheet.vue'

/**
 * # NPCList 컴포넌트
 * 
 * NPC 목록을 표시하고 검색/필터링 기능을 제공하는 컴포넌트
 * 물물교환 정보와 위치 정보를 연관하여 표시
 */

// NPC Store
const npcStore = useNpcStore()

// 검색어 상태
const searchQuery = ref('')
// 선택된 위치 필터
const selectedLocation = ref('')
// 물물교환 필터 (문자열로 처리)
const tradeFilter = ref('')
// Sheet 상태
const sheetOpen = ref(false)
const selectedNpc = ref<EnrichedNPC | null>(null)

/**
 * # 필터링된 NPC 목록
 * 
 * 검색어와 필터 조건에 따라 NPC 목록을 필터링
 */
const filteredNPCs = computed(() => {
  return npcStore.getFilteredNPCs({
    searchQuery: searchQuery.value,
    locationId: selectedLocation.value || undefined,
    hasTrades: tradeFilter.value ? tradeFilter.value === 'true' : undefined
  })
})

/**
 * # NPC 선택 핸들러
 * 
 * NPC를 클릭했을 때 호출되는 이벤트 핸들러
 * NPC 상세 정보 Sheet를 열고 선택된 NPC를 설정
 * 
 * @param npc - 선택된 NPC
 */
function selectNPC(npc: EnrichedNPC): void {
  selectedNpc.value = npc
  sheetOpen.value = true
}

/**
 * # 이미지 에러 핸들러
 * 
 * NPC 이미지 로드 실패 시 호출되는 핸들러
 * 
 * @param event - 이미지 에러 이벤트
 */
function handleImageError(event: Event): void {
  const img = event.target as HTMLImageElement
  img.style.display = 'none'
}
</script>

<style scoped>
/* 모바일에서 그리드 반응형 최적화 */
@media (max-width: 640px) {
  .grid {
    gap: 0.5rem;
  }
}

/* 카드 호버 효과 */
.bg-card:hover {
  transform: translateY(-1px);
  transition: transform 0.2s ease-in-out;
}
</style>

// src/components/data/NPCList.tsx
import { useEffect, useMemo, useState } from 'react'

import { useNpcDataStore, type EnrichedNPC } from '../../stores/npcDataStore'
import Input from '../ui/Input'
import { Select } from '../ui/select/Select'
import { SelectContent } from '../ui/select/SelectContent'
import { SelectItem } from '../ui/select/SelectItem'
import { SelectTrigger } from '../ui/select/SelectTrigger'
import { SelectValue } from '../ui/select/SelectValue'

function handleImageError(event: React.SyntheticEvent<HTMLImageElement>) {
  event.currentTarget.style.display = 'none'
}

export function NPCList() {
  const initialize = useNpcDataStore((state) => state.initialize)
  const locationCounts = useNpcDataStore((state) => state.locationCounts)
  const uniqueLocations = useNpcDataStore((state) => state.uniqueLocations)
  const getFilteredNPCs = useNpcDataStore((state) => state.getFilteredNPCs)

  const [searchQuery, setSearchQuery] = useState('')
  const [selectedLocation, setSelectedLocation] = useState('')
  const [tradeFilter, setTradeFilter] = useState('')
  const [selectedNpc, setSelectedNpc] = useState<EnrichedNPC | null>(null)

  useEffect(() => {
    initialize()
  }, [initialize])

  const filteredNPCs = useMemo(
    () =>
      getFilteredNPCs({
        searchQuery,
        locationId: selectedLocation || undefined,
        hasTrades: tradeFilter === '' ? undefined : tradeFilter === 'true',
      }),
    [getFilteredNPCs, searchQuery, selectedLocation, tradeFilter],
  )

  const locationOptions = useMemo(
    () => uniqueLocations.sort((a, b) => a.name.localeCompare(b.name)),
    [uniqueLocations],
  )

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-4 sm:flex-row">
        <Input
          value={searchQuery}
          onChange={(event) => setSearchQuery(event.target.value)}
          placeholder="NPC 이름, 설명, 위치로 검색..."
        />

        <div className="flex gap-2">
          <Select value={selectedLocation} onValueChange={setSelectedLocation}>
            <SelectTrigger className="w-40">
              <SelectValue>
                {selectedLocation
                  ? locationOptions.find((option) => option.id === selectedLocation)?.name ?? '위치 선택'
                  : '위치 선택'}
              </SelectValue>
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="">전체</SelectItem>
              {locationOptions.map((location) => (
                <SelectItem key={location.id} value={location.id}>
                  {location.name} ({locationCounts[location.id] ?? 0})
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          <Select value={tradeFilter} onValueChange={setTradeFilter}>
            <SelectTrigger className="w-32">
              <SelectValue>
                {tradeFilter === '' ? '교환 여부' : tradeFilter === 'true' ? '교환 가능' : '교환 불가'}
              </SelectValue>
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="">전체</SelectItem>
              <SelectItem value="true">교환 가능</SelectItem>
              <SelectItem value="false">교환 불가</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      <div className="text-sm text-muted-foreground">총 {filteredNPCs.length}개의 NPC</div>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 2xl:grid-cols-8">
        {filteredNPCs.map((npc) => (
          <button
            key={npc.id}
            type="button"
            className="cursor-pointer rounded-lg border border-border bg-card p-3 text-left transition-shadow hover:shadow-md"
            onClick={() => setSelectedNpc(npc)}
          >
            <div className="mb-2 flex aspect-square items-center justify-center overflow-hidden rounded-lg bg-muted">
              {npc.imageUrl ? (
                <img
                  src={npc.imageUrl}
                  alt={npc.name}
                  className="h-full w-full object-cover"
                  onError={handleImageError}
                />
              ) : (
                <span className="text-xs text-muted-foreground">이미지 없음</span>
              )}
            </div>
            <div className="space-y-1">
              <h3 className="text-sm font-semibold">{npc.name}</h3>
              <p className="line-clamp-2 text-xs text-muted-foreground">{npc.description}</p>
              <p className="text-xs text-muted-foreground">{npc.location.name}</p>
              {npc.tradeCount > 0 ? (
                <div className="flex items-center gap-1 text-xs text-blue-600">
                  <span>교환 가능</span>
                  <span className="rounded-full bg-blue-100 px-1 py-0.5 text-xs text-blue-800">
                    {npc.tradeCount}개
                  </span>
                </div>
              ) : (
                <div className="text-xs text-muted-foreground">교환 불가</div>
              )}
            </div>
          </button>
        ))}
      </div>

      {filteredNPCs.length === 0 ? (
        <div className="rounded-lg border py-12 text-center text-muted-foreground">
          검색 조건에 맞는 NPC가 없습니다.
        </div>
      ) : null}

      {selectedNpc ? (
        <div className="rounded-lg border border-border bg-card p-6">
          <div className="mb-4 flex items-start gap-4">
            <div className="h-24 w-24 flex-shrink-0 overflow-hidden rounded-lg bg-muted">
              {selectedNpc.imageUrl ? (
                <img
                  src={selectedNpc.imageUrl}
                  alt={selectedNpc.name}
                  className="h-full w-full object-cover"
                  onError={handleImageError}
                />
              ) : (
                <span className="flex h-full w-full items-center justify-center text-xs text-muted-foreground">
                  이미지 없음
                </span>
              )}
            </div>
            <div className="flex-1 space-y-2">
              <div>
                <h2 className="text-lg font-semibold">{selectedNpc.name}</h2>
                <p className="text-sm text-muted-foreground">{selectedNpc.description}</p>
              </div>
              <div className="flex flex-wrap gap-2 text-xs">
                <span className="rounded bg-muted px-2 py-1">{selectedNpc.location.name}</span>
                {selectedNpc.tradeCount > 0 ? (
                  <span className="rounded bg-blue-100 px-2 py-1 text-blue-800">
                    물물교환 가능 {selectedNpc.tradeCount}개
                  </span>
                ) : (
                  <span className="rounded bg-gray-100 px-2 py-1 text-gray-600">물물교환 불가</span>
                )}
              </div>
            </div>
            <button
              type="button"
              className="rounded-md border border-border px-2 py-1 text-sm text-muted-foreground hover:bg-muted"
              onClick={() => setSelectedNpc(null)}
            >
              닫기
            </button>
          </div>

          <div className="space-y-2">
            <h3 className="text-sm font-semibold text-foreground">물물교환 가능 아이템</h3>
            {selectedNpc.availableTrades.length > 0 ? (
              <div className="space-y-2">
                {selectedNpc.availableTrades.map((trade) => (
                  <div key={trade.tradeId} className="rounded border border-border bg-background p-3 text-sm">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="font-medium">
                        {trade.giveQuantity}x {trade.giveItemName}
                      </span>
                      <span className="text-muted-foreground">→</span>
                      <span className="font-medium">
                        {trade.receiveQuantity}x {trade.receiveItemName}
                      </span>
                    </div>
                    <div className="mt-1 text-xs text-muted-foreground">
                      {trade.type} · 최대 {trade.maxExchanges}회 교환 가능
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="rounded border border-dashed py-6 text-center text-sm text-muted-foreground">
                물물교환 가능한 아이템이 없습니다.
              </div>
            )}
          </div>
        </div>
      ) : null}
    </div>
  )
}

export default NPCList
