// src-react/components/data/RecipeList.tsx
import { useEffect, useMemo, useState } from 'react'

import { getItemById } from '../../lib/dataAccess'
import { formatTime } from '../../../src/utils/timeUtils'
import { useRecipeDataStore } from '../../stores/recipeDataStore'
import Input from '../ui/Input'
import { Select } from '../ui/select/Select'
import { SelectContent } from '../ui/select/SelectContent'
import { SelectItem } from '../ui/select/SelectItem'
import { SelectTrigger } from '../ui/select/SelectTrigger'
import { SelectValue } from '../ui/select/SelectValue'

function getItemName(itemId: string) {
  return getItemById(itemId)?.name ?? itemId
}

function getItemImageUrl(itemId: string) {
  return getItemById(itemId)?.imageUrl ?? '/images/items/default.webp'
}

function handleImageError(event: React.SyntheticEvent<HTMLImageElement>) {
  event.currentTarget.src = '/images/items/default.webp'
}

export function RecipeList() {
  const initialize = useRecipeDataStore((state) => state.initialize)
  const categories = useRecipeDataStore((state) => state.categories)
  const facilityLevels = useRecipeDataStore((state) => state.facilityLevels)
  const getFilteredRecipes = useRecipeDataStore((state) => state.getFilteredRecipes)

  const [searchQuery, setSearchQuery] = useState('')
  const [selectedCategory, setSelectedCategory] = useState('')
  const [selectedFacilityLevel, setSelectedFacilityLevel] = useState('')

  useEffect(() => {
    initialize()
  }, [initialize])

  const filteredRecipes = useMemo(
    () =>
      getFilteredRecipes({
        searchQuery,
        category: selectedCategory || undefined,
        facilityLevel: selectedFacilityLevel || undefined,
      }),
    [getFilteredRecipes, searchQuery, selectedCategory, selectedFacilityLevel],
  )

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-2 sm:flex-row">
        <Input
          value={searchQuery}
          onChange={(event) => setSearchQuery(event.target.value)}
          type="text"
          placeholder="레시피 이름 또는 ID로 검색..."
        />

        <Select value={selectedCategory} onValueChange={setSelectedCategory}>
          <SelectTrigger className="w-full sm:w-[200px]">
            <SelectValue>{selectedCategory || '모든 카테고리'}</SelectValue>
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="">모든 카테고리</SelectItem>
            {categories.map((category) => (
              <SelectItem key={category} value={category}>
                {category}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>

        <Select value={selectedFacilityLevel} onValueChange={setSelectedFacilityLevel}>
          <SelectTrigger className="w-full sm:w-[200px]">
            <SelectValue>
              {selectedFacilityLevel ? `Lv.${selectedFacilityLevel}` : '모든 레벨'}
            </SelectValue>
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="">모든 레벨</SelectItem>
            {facilityLevels.map((level) => (
              <SelectItem key={level} value={level.toString()}>
                Lv.{level}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="text-sm text-muted-foreground">총 {filteredRecipes.length}개의 레시피</div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
        {filteredRecipes.map((recipe) => {
          const resultItem = getItemById(recipe.resultItemId)
          return (
            <div
              key={recipe.id}
              className="rounded-lg border border-border bg-card p-4 transition-shadow hover:shadow-md"
            >
              <div className="flex items-start gap-4">
                <img
                  src={getItemImageUrl(recipe.resultItemId)}
                  alt={recipe.name}
                  className="h-16 w-16 flex-shrink-0 rounded object-cover"
                  onError={handleImageError}
                />
                <div className="min-w-0 flex-1">
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <h3 className="text-lg font-medium text-foreground">{recipe.name}</h3>
                      <p className="mt-1 text-sm text-muted-foreground">ID: {recipe.id}</p>
                    </div>
                    {recipe.resultQuantity && recipe.resultQuantity > 1 ? (
                      <span className="text-sm font-medium text-foreground">
                        x{recipe.resultQuantity}
                      </span>
                    ) : null}
                  </div>

                  <div className="mt-3 flex flex-wrap gap-2">
                    {recipe.category ? (
                      <span className="inline-flex items-center rounded-md border-2 border-slate-700 bg-slate-50 px-2.5 py-1 text-xs font-bold text-slate-950 dark:border-slate-500 dark:bg-slate-700 dark:text-slate-100">
                        {recipe.category}
                      </span>
                    ) : null}
                    {recipe.facilityLevel ? (
                      <span className="inline-flex items-center rounded-md border-2 border-blue-700 bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-950 dark:border-blue-500 dark:bg-blue-700 dark:text-blue-100">
                        요리 Lv.{recipe.facilityLevel}
                      </span>
                    ) : null}
                    {recipe.craftingTime ? (
                      <span className="inline-flex items-center rounded-md border-2 border-amber-600 bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-900 dark:border-amber-500 dark:bg-amber-700 dark:text-amber-100">
                        {formatTime(recipe.craftingTime)}
                      </span>
                    ) : null}
                  </div>

                  <div className="mt-4">
                    <p className="mb-2 text-sm font-medium text-foreground">필요 재료:</p>
                    <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
                      {recipe.requiredItems.map((material) => (
                        <div key={material.itemId} className="flex items-center gap-2 text-sm">
                          <img
                            src={getItemImageUrl(material.itemId)}
                            alt={getItemName(material.itemId)}
                            className="h-6 w-6 flex-shrink-0 rounded object-cover"
                            onError={handleImageError}
                          />
                          <span className="text-foreground">{getItemName(material.itemId)}</span>
                          <span className="ml-auto text-muted-foreground">x{material.quantity}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )
        })}
      </div>

      {filteredRecipes.length === 0 ? (
        <div className="rounded-lg border py-12 text-center text-muted-foreground">
          검색 조건에 맞는 레시피가 없습니다.
        </div>
      ) : null}
    </div>
  )
}

export default RecipeList

// src/components/data/RecipeList.vue
<template>
  <div class="space-y-4">
    <!-- 검색 및 필터 -->
    <div class="flex flex-col sm:flex-row gap-2">
      <Input v-model="searchQuery" type="text" placeholder="레시피 이름 또는 ID로 검색..." />

      <Select v-model="selectedCategory" default-value="">
        <SelectTrigger class="w-full sm:w-[200px]">
          <SelectValue placeholder="모든 카테고리" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="">모든 카테고리</SelectItem>
          <SelectItem v-for="category in recipesStore.categories" :key="category" :value="category">
            {{ category }}
          </SelectItem>
        </SelectContent>
      </Select>

      <Select v-model="selectedFacilityLevel" default-value="">
        <SelectTrigger class="w-full sm:w-[200px]">
          <SelectValue placeholder="모든 레벨" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="">모든 레벨</SelectItem>
          <SelectItem v-for="level in facilityLevels" :key="level" :value="level.toString()">
            Lv.{{ level }}
          </SelectItem>
        </SelectContent>
      </Select>
    </div>

    <div class="text-sm text-muted-foreground">
      총 {{ filteredRecipes.length }}개의 레시피
    </div>

    <!-- 레시피 그리드 -->
    <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">
      <div v-for="recipe in filteredRecipes" :key="recipe.id"
        class="border border-border rounded-lg p-4 hover:shadow-md transition-shadow bg-card">
        <div class="flex items-start gap-4">
          <img :src="getItemImageUrl(recipe.resultItemId)" :alt="recipe.name"
            class="w-16 h-16 object-cover rounded flex-shrink-0" @error="handleImageError" />
          <div class="flex-1 min-w-0">
            <div class="flex items-start justify-between">
              <div>
                <h3 class="font-medium text-lg text-foreground">{{ recipe.name }}</h3>
                <p class="text-sm text-muted-foreground mt-1">ID: {{ recipe.id }}</p>
              </div>
              <div class="text-right flex-shrink-0">
                <span v-if="recipe.resultQuantity && recipe.resultQuantity > 1"
                  class="text-sm font-medium text-foreground">
                  x{{ recipe.resultQuantity }}
                </span>
              </div>
            </div>

            <div class="flex flex-wrap gap-2 mt-3">
              <span v-if="recipe.category" class="inline-flex items-center px-2.5 py-1 text-xs font-bold rounded-md border-2 bg-slate-50 dark:bg-slate-700 text-slate-950 dark:text-slate-100 border-slate-700 dark:border-slate-500">
                {{ recipe.category }}
              </span>
              <span v-if="recipe.facilityLevel" class="inline-flex items-center px-2.5 py-1 text-xs font-bold rounded-md border-2 bg-blue-50 dark:bg-blue-700 text-blue-950 dark:text-blue-100 border-blue-700 dark:border-blue-500">
                요리 Lv.{{ recipe.facilityLevel }}
              </span>
            </div>

            <div class="mt-4">
              <p class="text-sm font-medium text-foreground mb-2">필요 재료:</p>
              <div class="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <div v-for="material in recipe.requiredItems" :key="material.itemId"
                  class="flex items-center gap-2 text-sm">
                  <img :src="getItemImageUrl(material.itemId)" :alt="getItemName(material.itemId)"
                    class="w-6 h-6 object-cover rounded flex-shrink-0" @error="handleImageError" />
                  <span class="text-foreground">
                    {{ getItemName(material.itemId) }}
                  </span>
                  <span class="text-muted-foreground ml-auto">x{{ material.quantity }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div v-if="filteredRecipes.length === 0" class="text-center py-12">
      <p class="text-muted-foreground">검색 조건에 맞는 레시피가 없습니다.</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRecipesStore } from '@/stores/recipes'
import { useItemStore } from '@/stores/item'
import Input from '@/components/ui/input.vue'
import Select from '@/components/ui/select.vue'
import SelectContent from '@/components/ui/select-content.vue'
import SelectItem from '@/components/ui/select-item.vue'
import SelectTrigger from '@/components/ui/select-trigger.vue'
import SelectValue from '@/components/ui/select-value.vue'

const recipesStore = useRecipesStore()
const itemStore = useItemStore()

const searchQuery = ref('')
const selectedCategory = ref('')
const selectedFacilityLevel = ref('')

// Store에서 데이터 로드
onMounted(() => {
  recipesStore.fetchRecipeList()
  itemStore.fetchItemList()
})

const facilityLevels = computed(() => {
  const levelSet = new Set<number>()
  recipesStore.recipeList.forEach(recipe => {
    if (recipe.facilityLevel) {
      levelSet.add(recipe.facilityLevel)
    }
  })
  return Array.from(levelSet).sort((a, b) => a - b)
})

const filteredRecipes = computed(() => {
  return recipesStore.recipeList.filter(recipe => {
    const matchesSearch = !searchQuery.value ||
      recipe.name.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
      recipe.id.toLowerCase().includes(searchQuery.value.toLowerCase())

    const matchesCategory = !selectedCategory.value || recipe.category === selectedCategory.value

    const matchesFacilityLevel = !selectedFacilityLevel.value ||
      recipe.facilityLevel?.toString() === selectedFacilityLevel.value

    return matchesSearch && matchesCategory && matchesFacilityLevel
  })
})

function getItemName(itemId: string) {
  const item = itemStore.getItemById(itemId)
  return item ? item.name : itemId
}

function getItemImageUrl(itemId: string) {
  const item = itemStore.getItemById(itemId)
  return item ? item.imageUrl : '/images/items/default.webp'
}

function handleImageError(event: Event) {
  const target = event.target as HTMLImageElement
  target.src = '/images/items/default.webp'
}
</script>
