// src/views/rune/components/RuneCard.vue
<template>
  <div class="border rounded-lg p-4 cursor-pointer hover:bg-muted/50 transition-colors" @click="$emit('click')">
    <div class="flex items-start gap-3">
      <!-- 룬 이미지 -->
      <div class="w-16 h-16 flex-shrink-0 border rounded bg-muted/50 flex items-center justify-center">
        <img v-if="rune.image" :src="rune.image" :alt="rune.name" class="w-full h-full object-contain" />
        <span v-else class="text-xs text-muted-foreground">
          이미지 없음
        </span>
      </div>

      <!-- 룬 정보 -->
      <div class="flex-1 min-w-0">
        <div class="flex items-start justify-between gap-2">
          <div class="flex-1 min-w-0">
            <h3 class="font-semibold text-sm truncate">
              {{ rune.name }}
            </h3>
            <div class="flex items-center gap-2 mt-1">
              <span :class="getRuneTypeBadgeClass(rune.type)">
                {{ rune.type }}
              </span>
              <span :class="getRuneGradeBadgeClass(rune.grade)">
                {{ rune.grade }}
              </span>
            </div>
          </div>
        </div>

        <!-- 효과 미리보기 (최대 2줄) -->
        <p class="text-xs text-muted-foreground mt-2 line-clamp-2">
          {{ rune.effect }}
        </p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
/**
 * # RuneCard 컴포넌트
 * 
 * ## 기능 설명
 * 개별 룬을 카드 형태로 표시하는 컴포넌트
 * 
 * ## 주요 기능
 * - 룬 이미지 표시 (없으면 placeholder)
 * - 룬 이름, 타입, 등급 표시
 * - 효과 미리보기 (2줄 제한)
 * - 클릭 시 상세 정보 열기
 */
import type { Rune } from '@/data/equip/weapons'
import { getRuneTypeBadgeClass, getRuneGradeBadgeClass } from '@/utils/runeUtils'

withDefaults(defineProps<{
  rune: Rune
}>(), {})

defineEmits<{
  click: []
}>()
</script>

// src-react/components/rune/RuneCard.tsx
import type { Rune } from '../../../src/data/equip/weapons'
import { getRuneGradeBadgeClass, getRuneTypeBadgeClass } from '../../../src/utils/runeUtils'

export interface RuneCardProps {
  rune: Rune
  onClick: (rune: Rune) => void
}

export function RuneCard({ rune, onClick }: RuneCardProps) {
  return (
    <button
      type="button"
      className="w-full cursor-pointer rounded-lg border border-border p-4 text-left transition-colors hover:bg-muted/50"
      onClick={() => onClick(rune)}
    >
      <div className="flex items-start gap-3">
        <div className="flex h-16 w-16 flex-shrink-0 items-center justify-center rounded border border-border bg-muted/50">
          {rune.image ? (
            <img src={rune.image} alt={rune.name} className="h-full w-full object-contain" />
          ) : (
            <span className="text-xs text-muted-foreground">이미지 없음</span>
          )}
        </div>

        <div className="min-w-0 flex-1">
          <div className="flex items-start justify-between gap-2">
            <div className="min-w-0 flex-1">
              <h3 className="truncate text-sm font-semibold text-foreground">{rune.name}</h3>
              <div className="mt-1 flex items-center gap-2">
                <span className={getRuneTypeBadgeClass(rune.type)}>{rune.type}</span>
                <span className={getRuneGradeBadgeClass(rune.grade)}>{rune.grade}</span>
              </div>
            </div>
          </div>

          <p className="mt-2 line-clamp-2 text-xs text-muted-foreground">{rune.effect}</p>
        </div>
      </div>
    </button>
  )
}

export default RuneCard
