// src/views/cooking/components/MaterialsSummary.vue
<template>
  <div>
    <h3 class="text-sm font-semibold text-foreground mb-2">총 필요 재료</h3>

    <div class="space-y-1">
      <div v-for="row in totalNeededRows" :key="'direct-' + row.itemId" class="space-y-1">
        <!-- 메인 아이템 -->
        <div class="flex items-center gap-2 text-sm">
          <img :src="getItemImageUrl(row.itemId)" :alt="getItemName(row.itemId)" class="w-5 h-5 rounded object-cover"
            @error="handleImageError" />
          <span class="truncate text-foreground">{{ getItemName(row.itemId) }}</span>
          <span class="ml-auto text-foreground">x{{ row.quantity }}</span>
          <span v-if="getBuyableCount(row.itemId) > 0" :class="[row.quantity > getBuyableCount(row.itemId)
            ? 'text-red-600 font-semibold bg-red-100 px-1 rounded border border-red-300'
            : 'text-muted-foreground']" class="ml-2 text-xs whitespace-nowrap">({{ row.quantity }}/{{
              getBuyableCount(row.itemId) }})
            <span v-if="row.quantity > getBuyableCount(row.itemId)" class="text-red-600 ml-1">⚠️</span>
          </span>
          <span v-if="getMinBuyPrice(row.itemId) !== null"
            class="ml-2 text-xs text-muted-foreground whitespace-nowrap">개당 {{
              formatGold(getMinBuyPrice(row.itemId)!) }} · 합계 {{ formatGold(getMinBuyPrice(row.itemId)! * row.quantity)
            }}</span>
        </div>

        <!-- 가공 레시피가 있는 경우 하위에 표시 -->
        <div v-if="getProcessedRecipe(row.itemId)" class="ml-7 space-y-1">
          <div v-for="ingredient in getProcessedRecipe(row.itemId)!.requiredItems" :key="ingredient.itemId"
            class="flex items-center gap-2 text-xs text-muted-foreground">
            <img :src="getItemImageUrl(ingredient.itemId)" :alt="getItemName(ingredient.itemId)"
              class="w-4 h-4 rounded object-cover" @error="handleImageError" />
            <span class="truncate">{{ getItemName(ingredient.itemId) }}</span>
            <span class="ml-auto">x{{ ingredient.quantity * Math.ceil(row.quantity /
              (getProcessedRecipe(row.itemId)!.resultQuantity || 1)) }}</span>
            <span v-if="getMinBuyPrice(ingredient.itemId) !== null"
              class="ml-2 text-muted-foreground whitespace-nowrap">개당 {{
                formatGold(getMinBuyPrice(ingredient.itemId)!) }} · 합계 {{ formatGold(getMinBuyPrice(ingredient.itemId)! *
                ingredient.quantity * Math.ceil(row.quantity / (getProcessedRecipe(row.itemId)!.resultQuantity || 1)))
              }}</span>
          </div>
        </div>
      </div>

      <!-- 총 필요 식재료 집계 -->
      <div v-if="totalRawMaterialsRows.length" class="pt-2 mt-2 border-t border-border">
        <div class="text-xs text-muted-foreground mb-1">총 필요 식재료</div>
        <div v-for="row in totalRawMaterialsRows" :key="'raw-' + row.itemId" class="space-y-1">
          <!-- 메인 아이템 -->
          <div class="flex items-center gap-2 text-sm">
            <img :src="getItemImageUrl(row.itemId)" :alt="getItemName(row.itemId)" class="w-5 h-5 rounded object-cover"
              @error="handleImageError" />
            <span class="truncate text-foreground">{{ getItemName(row.itemId) }}</span>
            <span class="ml-auto font-semibold text-foreground">x{{ row.quantity }}</span>
            <span v-if="getBuyableCount(row.itemId) > 0"
              :class="[row.quantity > getBuyableCount(row.itemId) ? 'text-destructive font-semibold' : 'text-muted-foreground']"
              class="ml-2 text-xs whitespace-nowrap">({{ row.quantity }}/{{ getBuyableCount(row.itemId) }})</span>
            <span v-if="getMinBuyPrice(row.itemId) !== null"
              class="ml-2 text-xs text-muted-foreground whitespace-nowrap">개당 {{
                formatGold(getMinBuyPrice(row.itemId)!) }} · 합계 {{ formatGold(getMinBuyPrice(row.itemId)! * row.quantity)
              }}</span>
          </div>

          <!-- 요리/가공 레시피가 있는 경우 하위에 표시 -->
          <div v-if="getProcessedRecipe(row.itemId)" class="ml-7 space-y-1">
            <div v-for="ingredient in getProcessedRecipe(row.itemId)!.requiredItems" :key="ingredient.itemId"
              class="flex items-center gap-2 text-xs text-muted-foreground">
              <img :src="getItemImageUrl(ingredient.itemId)" :alt="getItemName(ingredient.itemId)"
                class="w-4 h-4 rounded object-cover" @error="handleImageError" />
              <span class="truncate">{{ getItemName(ingredient.itemId) }}</span>
              <span class="ml-auto">x{{ ingredient.quantity * Math.ceil(row.quantity /
                (getProcessedRecipe(row.itemId)!.resultQuantity || 1)) }}</span>
              <span v-if="getMinBuyPrice(ingredient.itemId) !== null"
                class="ml-2 text-muted-foreground whitespace-nowrap">개당 {{
                  formatGold(getMinBuyPrice(ingredient.itemId)!) }} · 합계 {{ formatGold(getMinBuyPrice(ingredient.itemId)!
                  *
                  ingredient.quantity * Math.ceil(row.quantity / (getProcessedRecipe(row.itemId)!.resultQuantity || 1)))
                }}</span>
            </div>
          </div>
        </div>
        <div class="flex items-center justify-end gap-2 text-sm mt-2 pt-2 border-t border-border">
          <span class="text-foreground">총 골드 (식재료)</span>
          <span class="font-semibold text-foreground">{{ formatGold(totalRawMaterialsGold) }}</span>
        </div>
      </div>

      <div class="flex items-center justify-end gap-2 text-sm mt-2 pt-2 border-t border-border">
        <span class="text-foreground">총 골드</span>
        <span class="font-semibold text-foreground">{{ formatGold(totalGoldCombined) }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { Recipe, RecipeGroup } from '@/data/schemas/recipe'
import { RECIPE_CATEGORY } from '@/data/schemas/recipe'

const props = withDefaults(defineProps<{
  selectedCounts: Record<string, number>
  recipesGrouped: RecipeGroup[]
  items: Array<{ id: string; name: string; imageUrl: string; category?: string }>
}>(), {
  selectedCounts: () => ({} as Record<string, number>),
  recipesGrouped: () => ([] as RecipeGroup[])
})

function getItemName(itemId: string) {
  const it = props.items.find(i => i.id === itemId)
  return it ? it.name : itemId
}

function getItemImageUrl(itemId: string) {
  const it = props.items.find(i => i.id === itemId)
  return it ? it.imageUrl : '/images/items/default.webp'
}

function handleImageError(e: Event) {
  const t = e.target as HTMLImageElement
  t.src = '/images/items/default.webp'
}

function findRecipeById(id: string): Recipe | undefined {
  for (const g of props.recipesGrouped) {
    const r = g.recipeList.find(r => r.id === id)
    if (r) return r
  }
  return undefined
}

const totalNeeded = computed<Record<string, number>>(() => {
  const result: Record<string, number> = {}
  for (const [recipeId, count] of Object.entries(props.selectedCounts)) {
    if (!count) continue
    const recipe = findRecipeById(recipeId)
    if (!recipe) continue
    recipe.requiredItems.forEach(ri => {
      result[ri.itemId] = (result[ri.itemId] || 0) + ri.quantity * count
    })
  }
  return result
})

const totalNeededRows = computed(() => {
  return Object.entries(totalNeeded.value)
    .map(([itemId, quantity]) => ({ itemId, quantity }))
    .sort((a, b) => (getItemName(a.itemId) || '').localeCompare(getItemName(b.itemId) || ''))
})

const processRecipeMap = computed(() => {
  const map: Record<string, Recipe> = {}
  for (const g of props.recipesGrouped) {
    for (const r of g.recipeList) {
      // 요리, 가공, 식재료 가공 등 모든 제작 레시피 포함
      if (
        r.category === RECIPE_CATEGORY.COOK ||
        r.category === RECIPE_CATEGORY.PROCESS ||
        r.category === RECIPE_CATEGORY.PROCESS_FOOD ||
        r.category === RECIPE_CATEGORY.PROCESS_METAL ||
        r.category === RECIPE_CATEGORY.PROCESS_WOOD ||
        r.category === RECIPE_CATEGORY.PROCESS_LEATHER ||
        r.category === RECIPE_CATEGORY.PROCESS_FABRIC ||
        r.category === RECIPE_CATEGORY.PROCESS_MEDICINE
      ) {
        if (!map[r.resultItemId]) map[r.resultItemId] = r
      }
    }
  }
  return map
})

function getProcessedRecipe(itemId: string): Recipe | undefined {
  return processRecipeMap.value[itemId]
}

// 가공품을 제외한 순수 식재료만 집계
const totalRawMaterials = computed<Record<string, number>>(() => {
  const result: Record<string, number> = {}

  // 직접 필요한 재료 중 가공품이 아닌 것들
  for (const [itemId, quantity] of Object.entries(totalNeeded.value)) {
    if (!processRecipeMap.value[itemId]) {
      result[itemId] = quantity
    }
  }

  // 가공품의 원재료들 추가
  for (const [itemId, quantity] of Object.entries(totalNeeded.value)) {
    if (processRecipeMap.value[itemId]) {
      const recipe = processRecipeMap.value[itemId]
      const outQty = recipe.resultQuantity && recipe.resultQuantity > 0 ? recipe.resultQuantity : 1
      const actions = Math.ceil(quantity / outQty)

      for (const ingredient of recipe.requiredItems) {
        // 가공품의 원재료도 가공품인 경우는 제외 (순수 식재료만)
        if (!processRecipeMap.value[ingredient.itemId]) {
          result[ingredient.itemId] = (result[ingredient.itemId] || 0) + ingredient.quantity * actions
        }
      }
    }
  }

  return result
})

const totalRawMaterialsRows = computed(() => {
  return Object.entries(totalRawMaterials.value)
    .map(([itemId, quantity]) => ({ itemId, quantity }))
    .sort((a, b) => (getItemName(a.itemId) || '').localeCompare(getItemName(b.itemId) || ''))
})

const totalRawMaterialsGold = computed(() => {
  let sum = 0
  for (const [itemId, quantity] of Object.entries(totalRawMaterials.value)) {
    const price = getMinBuyPrice(itemId)
    if (price !== null) sum += price * quantity
  }
  return sum
})

function getMinBuyPrice(itemId: string): number | null {
  const prices: number[] = []
  props.recipesGrouped.forEach(g => {
    g.recipeList.forEach(r => {
      if (r.resultItemId !== itemId) return
      if (r.category !== RECIPE_CATEGORY.BUY) return
      const gold = r.requiredItems.find(ri => ri.itemId === 'gold')
      if (gold) prices.push(gold.quantity)
    })
  })
  if (prices.length === 0) return null
  return Math.min(...prices)
}

function getBuyableCount(itemId: string): number {
  // 집계: 같은 아이템을 판매하는 서로 다른 NPC * 30
  const npcSet = new Set<string>()
  props.recipesGrouped.forEach(g => {
    g.recipeList.forEach(r => {
      if (r.resultItemId !== itemId) return
      if (r.category !== RECIPE_CATEGORY.BUY) return
      const gold = r.requiredItems.find(ri => ri.itemId === 'gold' && ri.buyNpcId)
      if (gold && gold.buyNpcId) npcSet.add(gold.buyNpcId)
    })
  })
  return npcSet.size * 30
}

const totalGoldCombined = computed(() => {
  let sum = 0
  for (const [itemId, quantity] of Object.entries(totalNeeded.value)) {
    const price = getMinBuyPrice(itemId)
    if (price !== null) sum += price * quantity
  }
  return sum
})

function formatGold(v: number): string {
  return `${v.toLocaleString()}G`
}
</script>

// src-react/components/cooking/MaterialsSummary.tsx
import { useMemo } from 'react'

import type { Item } from '../../../src/data/schemas/item'
import type { Recipe, RecipeGroup } from '../../../src/data/schemas/recipe'
import { RECIPE_CATEGORY } from '../../../src/data/schemas/recipe'

export interface MaterialsSummaryProps {
  selectedCounts: Record<string, number>
  recipesGrouped: RecipeGroup[]
  items: Item[]
}

interface NeededRow {
  itemId: string
  quantity: number
}

function findRecipeById(groups: RecipeGroup[], id: string): Recipe | undefined {
  for (const group of groups) {
    const found = group.recipeList.find((recipe) => recipe.id === id)
    if (found) {
      return found
    }
  }
  return undefined
}

function formatGold(value: number): string {
  return `${value.toLocaleString()}G`
}

export function MaterialsSummary({ selectedCounts, recipesGrouped, items }: MaterialsSummaryProps) {
  const itemMap = useMemo(() => {
    const map = new Map<string, Item>()
    items.forEach((item) => map.set(item.id, item))
    return map
  }, [items])

  const processRecipeMap = useMemo(() => {
    const map = new Map<string, Recipe>()
    recipesGrouped.forEach((group) => {
      group.recipeList.forEach((recipe) => {
        if (
          recipe.category === RECIPE_CATEGORY.COOK ||
          recipe.category === RECIPE_CATEGORY.PROCESS ||
          recipe.category === RECIPE_CATEGORY.PROCESS_FOOD ||
          recipe.category === RECIPE_CATEGORY.PROCESS_METAL ||
          recipe.category === RECIPE_CATEGORY.PROCESS_WOOD ||
          recipe.category === RECIPE_CATEGORY.PROCESS_LEATHER ||
          recipe.category === RECIPE_CATEGORY.PROCESS_FABRIC ||
          recipe.category === RECIPE_CATEGORY.PROCESS_MEDICINE
        ) {
          if (!map.has(recipe.resultItemId)) {
            map.set(recipe.resultItemId, recipe)
          }
        }
      })
    })
    return map
  }, [recipesGrouped])

  const totalNeeded = useMemo(() => {
    const accumulator: Record<string, number> = {}
    Object.entries(selectedCounts).forEach(([recipeId, count]) => {
      if (!count) return
      const recipe = findRecipeById(recipesGrouped, recipeId)
      if (!recipe) return
      recipe.requiredItems.forEach((required) => {
        accumulator[required.itemId] = (accumulator[required.itemId] || 0) + required.quantity * count
      })
    })
    return accumulator
  }, [recipesGrouped, selectedCounts])

  const totalNeededRows: NeededRow[] = useMemo(
    () =>
      Object.entries(totalNeeded)
        .map(([itemId, quantity]) => ({ itemId, quantity }))
        .sort((a, b) => (itemMap.get(a.itemId)?.name ?? '').localeCompare(itemMap.get(b.itemId)?.name ?? '')),
    [itemMap, totalNeeded],
  )

  const totalRawMaterials = useMemo(() => {
    const accumulator: Record<string, number> = {}

    Object.entries(totalNeeded).forEach(([itemId, quantity]) => {
      if (!processRecipeMap.has(itemId)) {
        accumulator[itemId] = (accumulator[itemId] || 0) + quantity
      }
    })

    Object.entries(totalNeeded).forEach(([itemId, quantity]) => {
      const recipe = processRecipeMap.get(itemId)
      if (!recipe) return

      const resultQuantity = recipe.resultQuantity && recipe.resultQuantity > 0 ? recipe.resultQuantity : 1
      const actions = Math.ceil(quantity / resultQuantity)

      recipe.requiredItems.forEach((required) => {
        if (!processRecipeMap.has(required.itemId)) {
          accumulator[required.itemId] = (accumulator[required.itemId] || 0) + required.quantity * actions
        }
      })
    })

    return accumulator
  }, [processRecipeMap, totalNeeded])

  const totalRawMaterialsRows: NeededRow[] = useMemo(
    () =>
      Object.entries(totalRawMaterials)
        .map(([itemId, quantity]) => ({ itemId, quantity }))
        .sort((a, b) => (itemMap.get(a.itemId)?.name ?? '').localeCompare(itemMap.get(b.itemId)?.name ?? '')),
    [itemMap, totalRawMaterials],
  )

  function getItemName(itemId: string): string {
    return itemMap.get(itemId)?.name ?? itemId
  }

  function getItemImageUrl(itemId: string): string {
    return itemMap.get(itemId)?.imageUrl ?? '/images/items/default.webp'
  }

  function getProcessedRecipe(itemId: string): Recipe | undefined {
    return processRecipeMap.get(itemId)
  }

  function getMinBuyPrice(itemId: string): number | null {
    const prices: number[] = []
    recipesGrouped.forEach((group) => {
      group.recipeList.forEach((recipe) => {
        if (recipe.resultItemId !== itemId || recipe.category !== RECIPE_CATEGORY.BUY) return
        const gold = recipe.requiredItems.find((required) => required.itemId === 'gold')
        if (gold) {
          prices.push(gold.quantity)
        }
      })
    })
    if (prices.length === 0) return null
    return Math.min(...prices)
  }

  function getBuyableCount(itemId: string): number {
    const npcSet = new Set<string>()
    recipesGrouped.forEach((group) => {
      group.recipeList.forEach((recipe) => {
        if (recipe.resultItemId !== itemId || recipe.category !== RECIPE_CATEGORY.BUY) return
        const gold = recipe.requiredItems.find(
          (required) => required.itemId === 'gold' && required.buyNpcId,
        )
        if (gold?.buyNpcId) {
          npcSet.add(gold.buyNpcId)
        }
      })
    })
    return npcSet.size * 30
  }

  const totalRawMaterialsGold = useMemo(() => {
    let sum = 0
    Object.entries(totalRawMaterials).forEach(([itemId, quantity]) => {
      const price = getMinBuyPrice(itemId)
      if (price !== null) {
        sum += price * quantity
      }
    })
    return sum
  }, [totalRawMaterials])

  const totalGoldCombined = useMemo(() => {
    let sum = 0
    Object.entries(totalNeeded).forEach(([itemId, quantity]) => {
      const price = getMinBuyPrice(itemId)
      if (price !== null) {
        sum += price * quantity
      }
    })
    return sum
  }, [totalNeeded])

  const handleImageError = (event: React.SyntheticEvent<HTMLImageElement>) => {
    event.currentTarget.src = '/images/items/default.webp'
  }

  return (
    <div>
      <h3 className="mb-2 text-sm font-semibold text-foreground">총 필요 재료</h3>
      <div className="space-y-1">
        {totalNeededRows.map((row) => (
          <div key={`direct-${row.itemId}`} className="space-y-1">
            <div className="flex items-center gap-2 text-sm">
              <img
                src={getItemImageUrl(row.itemId)}
                alt={getItemName(row.itemId)}
                className="h-5 w-5 rounded object-cover"
                onError={handleImageError}
              />
              <span className="truncate text-foreground">{getItemName(row.itemId)}</span>
              <span className="ml-auto text-foreground">x{row.quantity}</span>
              {getBuyableCount(row.itemId) > 0 ? (
                <span
                  className={[
                    'ml-2 text-xs whitespace-nowrap',
                    row.quantity > getBuyableCount(row.itemId)
                      ? 'rounded border border-red-300 bg-red-100 px-1 font-semibold text-red-600'
                      : 'text-muted-foreground',
                  ].join(' ')}
                >
                  ({row.quantity}/{getBuyableCount(row.itemId)})
                  {row.quantity > getBuyableCount(row.itemId) ? <span className="ml-1 text-red-600">⚠️</span> : null}
                </span>
              ) : null}
              {getMinBuyPrice(row.itemId) !== null ? (
                <span className="ml-2 whitespace-nowrap text-xs text-muted-foreground">
                  개당 {formatGold(getMinBuyPrice(row.itemId)!)} · 합계{' '}
                  {formatGold(getMinBuyPrice(row.itemId)! * row.quantity)}
                </span>
              ) : null}
            </div>
            {getProcessedRecipe(row.itemId) ? (
              <div className="ml-7 space-y-1">
                {getProcessedRecipe(row.itemId)!.requiredItems.map((ingredient) => {
                  const recipe = getProcessedRecipe(row.itemId)!
                  const resultQuantity = recipe.resultQuantity && recipe.resultQuantity > 0 ? recipe.resultQuantity : 1
                  const actions = Math.ceil(row.quantity / resultQuantity)
                  const needed = ingredient.quantity * actions
                  return (
                    <div key={ingredient.itemId} className="flex items-center gap-2 text-xs text-muted-foreground">
                      <img
                        src={getItemImageUrl(ingredient.itemId)}
                        alt={getItemName(ingredient.itemId)}
                        className="h-4 w-4 rounded object-cover"
                        onError={handleImageError}
                      />
                      <span className="truncate">{getItemName(ingredient.itemId)}</span>
                      <span className="ml-auto">x{needed}</span>
                      {getMinBuyPrice(ingredient.itemId) !== null ? (
                        <span className="ml-2 whitespace-nowrap text-muted-foreground">
                          개당 {formatGold(getMinBuyPrice(ingredient.itemId)!)} · 합계{' '}
                          {formatGold(getMinBuyPrice(ingredient.itemId)! * needed)}
                        </span>
                      ) : null}
                    </div>
                  )
                })}
              </div>
            ) : null}
          </div>
        ))}

        {totalRawMaterialsRows.length > 0 ? (
          <div className="mt-2 border-t border-border pt-2">
            <div className="mb-1 text-xs text-muted-foreground">총 필요 식재료</div>
            {totalRawMaterialsRows.map((row) => (
              <div key={`raw-${row.itemId}`} className="space-y-1">
                <div className="flex items-center gap-2 text-sm">
                  <img
                    src={getItemImageUrl(row.itemId)}
                    alt={getItemName(row.itemId)}
                    className="h-5 w-5 rounded object-cover"
                    onError={handleImageError}
                  />
                  <span className="truncate text-foreground">{getItemName(row.itemId)}</span>
                  <span className="ml-auto font-semibold text-foreground">x{row.quantity}</span>
                  {getBuyableCount(row.itemId) > 0 ? (
                    <span
                      className={[
                        'ml-2 text-xs whitespace-nowrap',
                        row.quantity > getBuyableCount(row.itemId)
                          ? 'font-semibold text-destructive'
                          : 'text-muted-foreground',
                      ].join(' ')}
                    >
                      ({row.quantity}/{getBuyableCount(row.itemId)})
                    </span>
                  ) : null}
                  {getMinBuyPrice(row.itemId) !== null ? (
                    <span className="ml-2 whitespace-nowrap text-xs text-muted-foreground">
                      개당 {formatGold(getMinBuyPrice(row.itemId)!)} · 합계{' '}
                      {formatGold(getMinBuyPrice(row.itemId)! * row.quantity)}
                    </span>
                  ) : null}
                </div>
              </div>
            ))}
            <div className="mt-2 flex items-center justify-end gap-2 border-t border-border pt-2 text-sm">
              <span className="text-foreground">총 골드 (식재료)</span>
              <span className="font-semibold text-foreground">{formatGold(totalRawMaterialsGold)}</span>
            </div>
          </div>
        ) : null}

        <div className="mt-2 flex items-center justify-end gap-2 border-t border-border pt-2 text-sm">
          <span className="text-foreground">총 골드</span>
          <span className="font-semibold text-foreground">{formatGold(totalGoldCombined)}</span>
        </div>
      </div>
    </div>
  )
}

export default MaterialsSummary
