// src/components/data/LocationList.tsx
import { useEffect, useMemo, useState } from 'react'

import { useLocationDataStore } from '../../stores/locationDataStore'
import Input from '../ui/Input'

export function LocationList() {
  const initialize = useLocationDataStore((state) => state.initialize)
  const getFilteredLocations = useLocationDataStore((state) => state.getFilteredLocations)

  const [searchQuery, setSearchQuery] = useState('')

  useEffect(() => {
    initialize()
  }, [initialize])

  const filteredLocations = useMemo(
    () => getFilteredLocations({ searchQuery }),
    [getFilteredLocations, searchQuery],
  )

  return (
    <div className="space-y-4">
      <Input
        value={searchQuery}
        onChange={(event) => setSearchQuery(event.target.value)}
        placeholder="위치 이름 검색..."
      />

      {filteredLocations.length > 0 ? (
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {filteredLocations.map((location) => (
            <div
              key={location.id}
              className="rounded-lg border border-border bg-card p-4 transition-shadow hover:shadow-md"
            >
              <div className="space-y-3">
                <h3 className="text-lg font-semibold">{location.name}</h3>
                {location.npcs.length > 0 ? (
                  <div className="space-y-1">
                    <div className="text-xs font-medium text-muted-foreground">NPC</div>
                    <div className="flex flex-wrap gap-1">
                      {location.npcs.map((npc) => (
                        <span
                          key={npc.id}
                          className="rounded bg-blue-100 px-2 py-0.5 text-xs text-blue-800"
                        >
                          {npc.name}
                        </span>
                      ))}
                    </div>
                  </div>
                ) : (
                  <div className="text-xs text-muted-foreground">NPC 없음</div>
                )}
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="rounded-lg border py-12 text-center">
          <p className="text-lg font-medium">위치를 찾을 수 없습니다</p>
          <p className="text-sm text-muted-foreground">검색어를 변경해보세요</p>
        </div>
      )}
    </div>
  )
}

export default LocationList

// src/views/data/components/LocationList.vue
<template>
  <div class="space-y-4">
    <!-- 검색 -->
    <div class="flex flex-col sm:flex-row gap-4">
      <div class="flex-1">
        <Input
          v-model="searchQuery"
          placeholder="위치 이름 검색..."
          class="w-full"
        />
      </div>
    </div>

    <!-- Location 목록 -->
    <div v-if="filteredLocations.length > 0" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
      <div
        v-for="location in filteredLocations"
        :key="location.id"
        class="bg-card border border-border rounded-lg p-4 hover:shadow-md transition-shadow"
      >
        <div class="space-y-3">
          <h3 class="text-lg font-semibold">{{ location.name }}</h3>
          
          <!-- NPC 목록 -->
          <div v-if="location.npcs.length > 0" class="space-y-1">
            <div class="text-xs font-medium text-muted-foreground">NPC:</div>
            <div class="flex flex-wrap gap-1">
              <span
                v-for="npc in location.npcs"
                :key="npc.id"
                class="text-xs bg-blue-100 text-blue-800 px-2 py-0.5 rounded"
              >
                {{ npc.name }}
              </span>
            </div>
          </div>
          
          <!-- NPC 없음 -->
          <div v-else class="text-xs text-muted-foreground">
            NPC 없음
          </div>
        </div>
      </div>
    </div>

    <!-- 빈 상태 -->
    <div v-else class="text-center py-12">
      <p class="text-lg font-medium">위치를 찾을 수 없습니다</p>
      <p class="text-sm">검색어를 변경해보세요</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useLocationStore } from '@/stores/location.ts'
import Input from '@/components/ui/input.vue'

const locationStore = useLocationStore()

const searchQuery = ref('')

const filteredLocations = computed(() => {
  return locationStore.getFilteredLocations({
    searchQuery: searchQuery.value
  })
})

onMounted(() => {
  locationStore.initializeLocationList()
})
</script>

<style scoped>
@media (max-width: 640px) {
  .grid {
    gap: 0.5rem;
  }
}

.bg-card:hover {
  transform: translateY(-1px);
  transition: transform 0.2s ease-in-out;
}
</style>
