// src/components/ui/select-value.vue
<template>
  <span :class="cn('block truncate', props.class)">
    <slot />
  </span>
</template>

<script setup lang="ts">
import { cn } from '@/lib/utils'

export interface SelectValueProps {
  placeholder?: string
  class?: string
}

const props = withDefaults(defineProps<SelectValueProps>(), {})
</script>

// src-react/components/ui/select/SelectValue.tsx
import type { HTMLAttributes, PropsWithChildren } from 'react'

import { cn } from '../../../lib/utils'

export interface SelectValueProps
  extends HTMLAttributes<HTMLSpanElement>,
    PropsWithChildren {}

export function SelectValue({ className, children, ...props }: SelectValueProps) {
  return (
    <span className={cn('block truncate', className)} {...props}>
      {children}
    </span>
  )
}
