// src/components/ui/SectionTitle.vue
<template>
  <h2 :class="cn('font-bold text-foreground', sizeClasses[size], className)">
    <slot />
  </h2>
</template>

<script setup lang="ts">
import { cn } from '@/lib/utils'

const props = withDefaults(defineProps<{
  size?: 'sm' | 'md' | 'lg'
  className?: string
}>(), {
  size: 'md',
  className: ''
})

const sizeClasses = {
  sm: 'text-sm',
  md: 'text-xl',
  lg: 'text-2xl'
}
</script>

// src-react/components/ui/SectionTitle.tsx
import type { FC, PropsWithChildren } from 'react'

import { cn } from '../../lib/utils'

type SectionTitleSize = 'sm' | 'md' | 'lg'

const sizeClasses: Record<SectionTitleSize, string> = {
  sm: 'text-sm',
  md: 'text-xl',
  lg: 'text-2xl',
}

export interface SectionTitleProps {
  size?: SectionTitleSize
  className?: string
}

export const SectionTitle: FC<PropsWithChildren<SectionTitleProps>> = ({
  children,
  size = 'md',
  className = '',
}) => (
  <h2 className={cn('font-bold text-foreground', sizeClasses[size], className)}>
    {children}
  </h2>
)

export default SectionTitle
