// src/components/crafting/SelectedItems.vue
<template>
  <div class="selected-items">
    <h2 class="text-lg font-bold mb-2 text-foreground">선택된 항목</h2>
    <div v-if="hasSelectedItems" class="overflow-y-auto">
      <div v-for="(categoryItems, category) in selectedItemsByCategory" :key="category" class="mb-3">
        <div class="flex justify-between items-center mb-1 px-2">
          <h3 class="text-sm font-semibold text-foreground">{{ category }}</h3>
          <button class="text-xs text-destructive hover:text-destructive/80" @click="clearCategory(category)">
            모두 삭제
          </button>
        </div>

        <table class="w-full text-xs border-collapse mb-2">
          <thead class="bg-muted">
            <tr class="border-b border-border">
              <th class="text-left p-1 font-semibold text-foreground">항목</th>
              <th class="text-center p-1 font-semibold text-foreground w-16">횟수</th>
              <th class="text-center p-1 font-semibold text-foreground w-16">생산량</th>
              <th class="text-center p-1 font-semibold text-foreground w-24">작업</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="selectedItem in categoryItems" :key="selectedItem.recipe.id"
              class="border-b border-border hover:bg-accent/50">
              <td class="p-1">
                <div class="flex items-center gap-1">
                  <img :src="getItemImageUrlById(selectedItem.recipe.resultItemId)" :alt="selectedItem.recipe.name"
                    class="w-6 h-6 object-cover rounded border border-border">
                  <span class="font-medium text-foreground">{{ selectedItem.recipe.name }}</span>
                </div>
              </td>
              <td class="p-1 text-center text-foreground">{{ selectedItem.quantity }}회</td>
              <td class="p-1 text-center text-foreground">{{ getTotalQuantity(selectedItem) }}개</td>
              <td class="p-1">
                <div class="flex items-center justify-center gap-1">
                  <button
                    class="w-5 h-5 flex items-center justify-center rounded hover:bg-accent text-foreground border border-border"
                    @click="decrementItem(selectedItem.recipe)">
                    -
                  </button>
                  <button
                    class="w-5 h-5 flex items-center justify-center rounded hover:bg-accent text-foreground border border-border"
                    @click="incrementItem(selectedItem.recipe)">
                    +
                  </button>
                  <button
                    class="w-5 h-5 flex items-center justify-center rounded hover:bg-accent text-destructive border border-destructive"
                    @click="removeItem(selectedItem.recipe.id)">
                    ×
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div v-else class="text-center py-4 text-muted-foreground text-sm">
      선택된 항목이 없습니다
    </div>

    <button v-if="hasSelectedItems"
      class="w-full mt-2 py-1.5 bg-destructive hover:bg-destructive/90 text-destructive-foreground rounded text-sm"
      @click="clearAllItems">
      선택 초기화
    </button>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useCraftingStore } from '@/stores/crafting';
import { getItemImageUrlById } from '@/utils/itemUtils';
import type { Recipe } from '@/data/schemas/recipe';

const craftingStore = useCraftingStore();

// 카테고리별로 그룹화된 선택된 항목들
const selectedItemsByCategory = computed(() => craftingStore.selectedItemsByCategory);

// 선택된 항목이 있는지 확인
const hasSelectedItems = computed(() => craftingStore.hasSelectedItems);

// 항목 수량 증가 함수
function incrementItem(recipe: Recipe) {
  craftingStore.selectItem(recipe, 1);
}

// 항목 수량 감소 함수
function decrementItem(recipe: Recipe) {
  craftingStore.selectItem(recipe, -1);
}

// 항목 삭제 함수
function removeItem(recipeId: string) {
  craftingStore.removeItem(recipeId);
}

// 카테고리 초기화 함수
function clearCategory(category: string) {
  craftingStore.clearCategory(category);
}

// 모든 선택 초기화 함수
function clearAllItems() {
  craftingStore.clearSelectedItems();
}

// 총 생산 개수를 계산하는 함수
function getTotalQuantity(selectedItem: { recipe: Recipe; quantity: number }): number {
  return selectedItem.quantity * (selectedItem.recipe.resultQuantity || 1);
}
</script>

<style scoped>
.selected-items {
  min-width: 300px;
  width: 100%;
}
</style>

// src-react/components/crafting/SelectedItems.tsx
import { getItemImageUrlById } from '../../../src/utils/itemUtils'
import type { Recipe } from '../../../src/data/schemas/recipe'
import {
  useCraftingStore,
  selectHasSelectedItems,
  selectSelectedItemsByCategory,
} from '../../stores/craftingStore'

function getTotalQuantity(selectedItem: { recipe: Recipe; quantity: number }) {
  return selectedItem.quantity * (selectedItem.recipe.resultQuantity ?? 1)
}

export function SelectedItems() {
  const selectedItemsByCategory = useCraftingStore(selectSelectedItemsByCategory)
  const hasSelectedItems = useCraftingStore(selectHasSelectedItems)
  const selectItem = useCraftingStore((state) => state.selectItem)
  const removeItem = useCraftingStore((state) => state.removeItem)
  const clearCategory = useCraftingStore((state) => state.clearCategory)
  const clearSelectedItems = useCraftingStore((state) => state.clearSelectedItems)

  if (!hasSelectedItems) {
    return (
      <div className="selected-items min-w-[300px] w-full">
        <h2 className="mb-2 text-lg font-bold text-foreground">선택된 항목</h2>
        <div className="rounded border border-dashed border-border py-4 text-center text-sm text-muted-foreground">
          선택된 항목이 없습니다
        </div>
      </div>
    )
  }

  return (
    <div className="selected-items min-w-[300px] w-full">
      <h2 className="mb-2 text-lg font-bold text-foreground">선택된 항목</h2>
      <div className="max-h-[320px] overflow-y-auto">
        {Object.entries(selectedItemsByCategory).map(([category, items]) => (
          <div key={category} className="mb-3">
            <div className="mb-1 flex items-center justify-between px-2">
              <h3 className="text-sm font-semibold text-foreground">{category}</h3>
              <button
                type="button"
                className="rounded border border-red-300 bg-red-100 px-2 py-1 text-xs font-medium text-red-600 transition-colors hover:border-red-400 hover:bg-red-200 hover:text-red-700 dark:border-red-800 dark:bg-red-950 dark:text-red-400 dark:hover:bg-red-900 dark:hover:text-red-300"
                onClick={() => clearCategory(category)}
                title="이 카테고리의 모든 항목 삭제"
              >
                모두 삭제
              </button>
            </div>
            <table className="mb-2 w-full border-collapse text-xs">
              <thead className="bg-muted">
                <tr className="border-border border-b">
                  <th className="p-1 text-left font-semibold text-foreground">항목</th>
                  <th className="w-16 p-1 text-center font-semibold text-foreground">횟수</th>
                  <th className="w-16 p-1 text-center font-semibold text-foreground">생산량</th>
                  <th className="w-24 p-1 text-center font-semibold text-foreground">작업</th>
                </tr>
              </thead>
              <tbody>
                {items.map((selectedItem) => (
                  <tr key={selectedItem.recipe.id} className="border-border border-b hover:bg-accent/50">
                    <td className="p-1">
                      <div className="flex items-center gap-1">
                        <img
                          src={getItemImageUrlById(selectedItem.recipe.resultItemId)}
                          alt={selectedItem.recipe.name}
                          className="h-6 w-6 rounded border border-border object-cover"
                        />
                        <span className="font-medium text-foreground">{selectedItem.recipe.name}</span>
                      </div>
                    </td>
                    <td className="p-1 text-center text-foreground">{selectedItem.quantity}회</td>
                    <td className="p-1 text-center text-foreground">{getTotalQuantity(selectedItem)}개</td>
                    <td className="p-1">
                      <div className="flex items-center justify-center gap-1">
                        <button
                          type="button"
                          className="flex h-6 w-6 items-center justify-center rounded border border-gray-300 bg-gray-200 font-bold text-gray-700 transition-colors hover:border-blue-400 hover:bg-blue-200 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300 dark:hover:border-blue-600 dark:hover:bg-blue-950 dark:hover:text-blue-300"
                          onClick={() => selectItem(selectedItem.recipe, -1)}
                          title="횟수 감소"
                        >
                          -
                        </button>
                        <button
                          type="button"
                          className="flex h-6 w-6 items-center justify-center rounded border border-gray-300 bg-gray-200 font-bold text-gray-700 transition-colors hover:border-blue-400 hover:bg-blue-200 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300 dark:hover:border-blue-600 dark:hover:bg-blue-950 dark:hover:text-blue-300"
                          onClick={() => selectItem(selectedItem.recipe, 1)}
                          title="횟수 증가"
                        >
                          +
                        </button>
                        <button
                          type="button"
                          className="flex h-6 w-6 items-center justify-center rounded border border-red-300 bg-red-100 font-bold text-red-600 transition-colors hover:border-red-400 hover:bg-red-200 hover:text-red-700 dark:border-red-800 dark:bg-red-950 dark:text-red-400 dark:hover:border-red-700 dark:hover:bg-red-900 dark:hover:text-red-300"
                          onClick={() => removeItem(selectedItem.recipe.id)}
                          title="항목 삭제"
                        >
                          ×
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ))}
      </div>
      <button
        type="button"
        className="mt-2 w-full rounded border border-red-600 bg-red-600 py-2 text-sm font-semibold text-white transition-colors hover:border-red-700 hover:bg-red-700 dark:bg-red-700 dark:hover:bg-red-800"
        onClick={() => clearSelectedItems()}
        title="모든 선택 항목 초기화"
      >
        선택 초기화
      </button>
    </div>
  )
}

export default SelectedItems
