// src/components/ui/card.vue
<template>
  <div :class="cn('rounded-lg border bg-card text-card-foreground shadow-sm', props.class)">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { cn } from '@/lib/utils'

export interface CardProps {
  class?: string
}

const props = withDefaults(defineProps<CardProps>(), {})
</script>

// src/components/ui/Card.tsx
import type { FC, HTMLAttributes } from 'react'

import { cn } from '../../lib/utils'

export interface CardProps extends HTMLAttributes<HTMLDivElement> {}

export const Card: FC<CardProps> = ({ className, ...props }) => (
  <div
    className={cn('rounded-lg border bg-card text-card-foreground shadow-sm', className)}
    {...props}
  />
)

export default Card
