// src/components/ui/CardTitle.tsx
import type { FC, HTMLAttributes } from 'react'

import { cn } from '../../lib/utils'

export interface CardTitleProps extends HTMLAttributes<HTMLHeadingElement> {}

export const CardTitle: FC<CardTitleProps> = ({ className, ...props }) => (
  <h3
    className={cn('text-2xl font-semibold leading-none tracking-tight', className)}
    {...props}
  />
)

export default CardTitle

// src/components/ui/card-title.vue
<template>
  <h3 :class="cn('text-2xl font-semibold leading-none tracking-tight', props.class)">
    <slot />
  </h3>
</template>

<script setup lang="ts">
import { cn } from '@/lib/utils'

export interface CardTitleProps {
  class?: string
}

const props = withDefaults(defineProps<CardTitleProps>(), {})
</script>
