// src/components/ui/CategoryTitle.tsx
import type { FC, PropsWithChildren } from 'react'

import { cn } from '../../lib/utils'

type CategoryTitleSize = 'xs' | 'sm' | 'md' | 'lg'

const sizeClasses: Record<CategoryTitleSize, string> = {
  xs: 'text-xs',
  sm: 'text-sm',
  md: 'text-base',
  lg: 'text-xl',
}

export interface CategoryTitleProps {
  size?: CategoryTitleSize
  className?: string
}

export const CategoryTitle: FC<PropsWithChildren<CategoryTitleProps>> = ({
  children,
  size = 'md',
  className = '',
}) => (
  <h3 className={cn('font-semibold text-foreground', sizeClasses[size], className)}>
    {children}
  </h3>
)

export default CategoryTitle

// src/components/ui/CategoryTitle.vue
<template>
  <h3 :class="cn('font-semibold text-foreground', sizeClasses[size], className)">
    <slot />
  </h3>
</template>

<script setup lang="ts">
import { cn } from '@/lib/utils'

const props = withDefaults(defineProps<{
  size?: 'xs' | 'sm' | 'md' | 'lg'
  className?: string
}>(), {
  size: 'md',
  className: ''
})

const sizeClasses = {
  xs: 'text-xs',
  sm: 'text-sm',
  md: 'text-base',
  lg: 'text-xl'
}
</script>
