// src/components/ui/PageTitle.tsx
import type { FC, PropsWithChildren } from 'react'

import { cn } from '../../lib/utils'

type PageTitleSize = 'sm' | 'md' | 'lg'

const sizeClasses: Record<PageTitleSize, string> = {
  sm: 'text-lg',
  md: 'text-2xl',
  lg: 'text-3xl',
}

export interface PageTitleProps {
  size?: PageTitleSize
  className?: string
}

export const PageTitle: FC<PropsWithChildren<PageTitleProps>> = ({
  children,
  size = 'lg',
  className = '',
}) => (
  <h1 className={cn('font-bold text-foreground', sizeClasses[size], className)}>
    {children}
  </h1>
)

export default PageTitle

// src/components/ui/PageTitle.vue
<template>
  <h1 :class="cn('font-bold text-foreground', sizeClasses[size], className)">
    <slot />
  </h1>
</template>

<script setup lang="ts">
import { cn } from '@/lib/utils'

const props = withDefaults(defineProps<{
  size?: 'sm' | 'md' | 'lg'
  className?: string
}>(), {
  size: 'lg',
  className: ''
})

const sizeClasses = {
  sm: 'text-lg',
  md: 'text-2xl',
  lg: 'text-3xl'
}
</script>
