// src/components/ui/tabs/TabsTrigger.tsx
import type { ButtonHTMLAttributes } from 'react'

import { cn } from '../../../lib/utils'
import { useTabsContext } from './TabsContext'

export interface TabsTriggerProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  value: string
}

export function TabsTrigger({ value, className, children, ...props }: TabsTriggerProps) {
  const { value: activeValue, onSelect } = useTabsContext('TabsTrigger')
  const isActive = activeValue === value

  return (
    <button
      type="button"
      role="tab"
      aria-selected={isActive}
      data-state={isActive ? 'active' : 'inactive'}
      className={cn(
        'inline-flex items-center justify-center whitespace-nowrap rounded-md px-3 py-1 text-sm font-medium transition-colors',
        'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
        'disabled:pointer-events-none disabled:opacity-50',
        isActive
          ? 'bg-primary text-primary-foreground shadow'
          : 'bg-muted text-muted-foreground hover:bg-muted/80',
        className,
      )}
      onClick={() => onSelect(value)}
      {...props}
    >
      {children}
    </button>
  )
}

export default TabsTrigger

// src/components/ui/tabs-trigger.vue
<template>
  <button :class="cn(
    'inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
    isActive
      ? 'bg-background text-foreground shadow-sm'
      : 'text-muted-foreground hover:text-foreground',
    props.class
  )" @click="handleClick">
    <slot />
  </button>
</template>

<script setup lang="ts">
import { computed, inject } from 'vue'
import { cn } from '@/lib/utils'

export interface TabsTriggerProps {
  value: string
  class?: string
}

const props = defineProps<TabsTriggerProps>()

const tabsContext = inject<{
  activeValue: { value: string }
  updateValue: (value: string) => void
}>('tabs')

if (!tabsContext) {
  throw new Error('TabsTrigger must be used within a Tabs component')
}

const isActive = computed(() => tabsContext.activeValue.value === props.value)

const handleClick = () => {
  tabsContext.updateValue(props.value)
}
</script>
